package uk.co.instanto.client.service;

import dev.verrai.rpc.common.transport.Transport;
import dev.verrai.rpc.common.transport.stomp.StompClient;
import uk.co.instanto.client.service.transport.StompTransport;

public class StompConfigurator {

    public static void configure(UnitRegistry registry, String localNodeId, StompClient client) {
        registry.setLocalNodeId(localNodeId);

        // Resolver: /topic/{targetNodeId}
        registry.setTransportResolver(targetNodeId -> new StompTransport(client,
                "/topic/" + targetNodeId, "/topic/" + localNodeId));

        // Setup EventBus
        EventBus eventBus = new EventBus(localNodeId);
        // Use a dedicated topic for cross-node events, e.g., /topic/events
        StompTransport eventTransport = new StompTransport(
                client, "/topic/discovery", "/topic/discovery");
        eventBus.addTransport(eventTransport);
        registry.setEventBus(eventBus);

        // Register Codecs (Identity Codecs for Protos)
        // These classes are generated by Wire, so they should be available if annotation processor ran
        registerIdentityCodec(eventBus, uk.co.instanto.client.service.dto.proto.NodeAnnouncedEvent.class,
                uk.co.instanto.client.service.dto.proto.NodeAnnouncedEvent.ADAPTER);
        registerIdentityCodec(eventBus, uk.co.instanto.client.service.dto.proto.NodeHeartbeatEvent.class,
                uk.co.instanto.client.service.dto.proto.NodeHeartbeatEvent.ADAPTER);
        registerIdentityCodec(eventBus, uk.co.instanto.client.service.dto.proto.NodeDepartedEvent.class,
                uk.co.instanto.client.service.dto.proto.NodeDepartedEvent.ADAPTER);

        registry.startDiscovery(localNodeId);

        registry.loadGeneratedCodecs();

        // Init RpcServer for inbound requests (listening on /topic/localNodeId)
        StompTransport serverTransport = new StompTransport(
                client, null, "/topic/" + localNodeId);

        registry.initRpcServer(serverTransport);
    }

    private static <T extends com.squareup.wire.Message<T, ?>> void registerIdentityCodec(EventBus eventBus, Class<T> cls,
            com.squareup.wire.ProtoAdapter<T> adapter) {
        eventBus.registerCodec(cls, new dev.verrai.rpc.common.codec.Codec<T, T>() {
            @Override
            public T toWire(T domain) {
                return domain;
            }

            @Override
            public T fromWire(T wire) {
                return wire;
            }

            @Override
            public com.squareup.wire.ProtoAdapter<T> getWireAdapter() {
                return adapter;
            }
        });
    }
}
